name: Cron test

on:
  schedule:
    # The shortest interval is every 5 minutes. Times are in UTC.
    - cron: '*/5 * * * *'

jobs:
  five-min-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Perform a task
        run: |
          echo "This workflow runs every 5 minutes."
          # Add the commands for your task here
